### PR TITLE
Brivia/task 2 Dynamic Functionality

### PR DESCRIPTION
**Pull request by MoonTheRipper**
# Added Dynamic Functionality to Code
- Instead of using only ```/bin/ls```, ```ls``` can now be used as well
- I have created an if condition that evaluates the presence of a `/` in the beginning of the ```commandLine```.
- It then chooses to copy the command onto a ```command``` array which added unto it, the string```"/bin/"``` Depending of the satisfaction of the ```if``` statement.

# Removed Bulky Code
- Created another function to handle the forking.
```letsForkIt```
- The Function creates a new fork and handles errors.

### CODE REVIEW

**Comment by briviamoon** [comment]
# Removed Bulky Code
- Created another function to handle the forking.
```letsForkIt```
- The Function creates a new fork and handles errors.

**Comment by DennisMakaka** [comment]
What if we define specific error codes (EXEC_FAILURE and FORK_FAILURE) to provide better context in case of failures?
And also replace printf statements with fprintf to write error messages to the standard error stream for better traceability.

**Comment by MoonTheRipper** [comment]
The printfs were only for testing.
I have updated files that have perror calls on errors.
I am currently trying to form a data structure that effectively deals with cd and its arguments.
I need to pass the environment variables in a way that execve can parse through all of them.

**Comment by briviamoon** [comment]
The printfs were only for testing.
I have updated files that have perror calls on errors.
I am currently trying to form a data structure that effectively deals with cd and its arguments.
I need to pass the environment variables in a way that execve can parse through all of them.

**Review by DennisMakaka — APPROVED** [review]

**Pull request merged**
